const express = require('express')
const app = express()
const {connectDB,connStatus} = require("./Database")
const {Index,About,Pricing,Portfolio,FAQ,Blog,Contact,Reset,Login,Register} = require("./controllers/BaseController")
app.set('view engine','ejs')
app.use(express.static('resources'))
// app.set('view')
connectDB()
app.listen(3000)
app.get('/',Index)
.get('/About',About)
.get('/Pricing',Pricing)
.get('/Portfolio',Portfolio)
.get('/FAQ',FAQ)
.get('/Blog',Blog)
.get('/Contact',Contact)
.get('/Reset/',Reset)
.get('/Login',Login)
.get('/Register',Register)
.use((req,res)=>{
    res.render('pages/Error.ejs',{title:'Error!!! Not Found'})
})